name: Change request
description: Request a change to the documentation
title: "[Change]: "
labels: ["documentation :book:"]
body:
  - type: markdown
    attributes:
      value: |
        If you think our documentation needs to be updated, fill out this form with details of what needs to be updated.
  - type: input
    id: url
    attributes:
      label: Page URL
      description: Provide a link to the page that needs to be updated, either on the site itself or in GitHub.
      placeholder: https://sdk-docs.adjust.com/en/index.html
    validations:
      required: true
  - type: textarea
    id: change-summary
    attributes:
      label: Change request summary
      description: Give a succinct summary of what needs to be updated on this page.
      placeholder: "This code snippet needs to be updated."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: "Provide any useful additional information. For example: links to external documentation or a changelog entry."
      placeholder: "This method is deprecated. See Google's documentation for more information: https://developer.android.com/docs"
    validations:
      required: false
  - type: dropdown
    id: affected-platforms
    attributes:
      label: Which platforms are affected by this change?
      description: Let us know which platform documentation we need to update. Leave blank if you're unsure.
      multiple: true
      options:
        - "iOS"
        - "Android"
        - "Unity"
        - "Web"
    validations:
      required: false
