extends: existence
message: "Avoid the gerund form (ing word). Use an imperative verb instead."
link: https://adjustcom.atlassian.net/wiki/spaces/PCS/pages/822771754/Style+Guide
level: warning
tokens:
  - '^\w*ing.*'
