extends: existence
message: "Titles and headings should not start with a gerund (verb ending in ing). Use an imperative verb instead."
link: https://adjustcom.atlassian.net/wiki/spaces/PCS/pages/822771754/Style+Guide
level: warning
scope: heading
tokens:
  - '^\w*ing.*'
