name: Fix translations
on:
  pull_request:
jobs:
  i18n-fixes:
    name: Fix translated files
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'smartling')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.ADJUST_NPM_TOKEN }}
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run translation fixes script
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python .github/scripts/fix_i18n.py
      - name: Check for modified files
        id: git-check
        run: echo "MODIFIED=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"
      - name: Set up node
        if: ${{ steps.git-check.outputs.MODIFIED == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://npm.pkg.github.com/
          scope: "@adjust"
      - name: Install dependencies
        if: ${{ steps.git-check.outputs.MODIFIED == 'true' }}
        run: npm i
      - name: Commit changes
        if: ${{ steps.git-check.outputs.MODIFIED == 'true' }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Fix translated files"
          git push
