name: Fix translations
on:
  pull_request:
  workflow_dispatch:
jobs:
  i18n-fixes:
    name: Fix translated files
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Run translation fixes script
        run: sh .github/scripts/fix-i18n.sh
      - name: Commit changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -am "Fix translated files"
          git push
