name: "PR Docs preview"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry install && poetry run sphinx-build . _build
      working-directory: docs
    - uses: actions/upload-artifact@v3
      with:
        name: HTML preview
        path: docs/_build/
        token: ${{ secrets.GITHUB_TOKEN }}
