name: "PR Docs preview"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry install
      working-directory: docs
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: docs/_build/html/
        token: ${{ secrets.GITHUB_TOKEN }}
