name: Update translations
on:
  push:
    branches:
      - main
      - v5

jobs:
  translations:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update translations
      CI_COMMIT_AUTHOR: github-actions[bot]
      CI_COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
        working-directory: docs
      - run: ./.github/scripts/translations.sh
      - name: Commit translations
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "No changes to commit"
            exit 0
          else
            git add .
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
