name: Style guide check
on:
  pull_request:
jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'smartling-*') == false
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: '["src/content/docs"]'
          fail_on_error: true
          filter_mode: diff_context
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
