name: Style guide check
on:
  pull_request:
jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'smartling') && !startsWith(github.head_ref, 'renovate') }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: '["src/content/docs"]'
          filter_mode: diff_context
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
