name: Style guide check
on: [pull_request]

jobs:
  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: '["src/content/docs/en"]'
          fail_on_error: true
          filter_mode: diff_context
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
